services:
  db:
    container_name: "mariadb"
    image: mariadb:lts-ubi9
    restart: unless-stopped
    env_file:
      - ".env"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./db_data:/var/lib/mysql

  phpmyadmin:
    container_name: "phpmyadmin"
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "${DB_GUI_PORT}:80"
    environment:
      PMA_HOST: db
      PMA_PORT: ${DB_PORT}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    